/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';


import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import {ArbeitstageDTO} from '../model/arbeitstageDTO';
import {FerienDTO} from '../model/ferienDTO';
import {ArbeitszeitDTO} from '../model/arbeitszeitDTO';


@Injectable()
export class SettingsControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * deleteFerien
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteFerienUsingDELETE(id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteFerienUsingDELETE(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteFerienUsingDELETE(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteFerienUsingDELETE(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteFerienUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/settings/ferien/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllFerien
     * 
     * @param email email
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllFerienUsingGET(email: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getAllFerienUsingGET(email: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getAllFerienUsingGET(email: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getAllFerienUsingGET(email: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling getAllFerienUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/settings/ferien/${encodeURIComponent(String(email))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getDays
     * 
     * @param email email
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDaysUsingGET(email: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getDaysUsingGET(email: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getDaysUsingGET(email: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getDaysUsingGET(email: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling getDaysUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/settings/arbeitstage/${encodeURIComponent(String(email))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * setDays
     * 
     * @param email email
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setDaysUsingPOST(email: string, arbeitstageDto: ArbeitstageDTO, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public setDaysUsingPOST(email: string, arbeitstageDto: ArbeitstageDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public setDaysUsingPOST(email: string, arbeitstageDto: ArbeitstageDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public setDaysUsingPOST(email: string, arbeitstageDto: ArbeitstageDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling setDaysUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/settings/arbeitstage/${encodeURIComponent(String(email))}`,
            arbeitstageDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * setFerien
     * 
     * @param email email
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setFerienUsingPOST(email: string, ferienDto: FerienDTO, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public setFerienUsingPOST(email: string, ferienDto: FerienDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public setFerienUsingPOST(email: string, ferienDto: FerienDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public setFerienUsingPOST(email: string, ferienDto: FerienDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling setFerienUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/settings/ferien/${encodeURIComponent(String(email))}`,
            ferienDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateDays
     * 
     * @param email email
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateDaysUsingPUT(email: string, arbeitstageDto: ArbeitstageDTO, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateDaysUsingPUT(email: string, arbeitstageDto: ArbeitstageDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateDaysUsingPUT(email: string, arbeitstageDto: ArbeitstageDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateDaysUsingPUT(email: string, arbeitstageDto: ArbeitstageDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling updateDaysUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.put<any>(`${this.basePath}/settings/arbeitstage/${encodeURIComponent(String(email))}`,
            arbeitstageDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }
    /**
     * updateArbeitszeit
     *
     * @param email email
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateArbeitszeitUsingPUT(email: string, arbeitszeitDTO: ArbeitszeitDTO, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateArbeitszeitUsingPUT(email: string, arbeitszeitDTO: ArbeitszeitDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateArbeitszeitUsingPUT(email: string, arbeitszeitDTO: ArbeitszeitDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateArbeitszeitUsingPUT(email: string, arbeitszeitDTO: ArbeitszeitDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling updateArbeitszeitUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.put<any>(`${this.basePath}/settings/arbeitszeit/${encodeURIComponent(String(email))}`,
            arbeitszeitDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * setArbeitszeit
     *
     * @param email email
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setArbeitszeitUsingPOST(email: string, arbeitszeitDTO: ArbeitszeitDTO, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public setArbeitszeitUsingPOST(email: string, arbeitszeitDTO: ArbeitszeitDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public setArbeitszeitUsingPOST(email: string, arbeitszeitDTO: ArbeitszeitDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public setArbeitszeitUsingPOST(email: string, arbeitszeitDTO: ArbeitszeitDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling setArbeitszeitUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/settings/arbeitszeit/${encodeURIComponent(String(email))}`,
            arbeitszeitDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getArbeitszeit
     *
     * @param email email
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getArbeitszeitUsingGET(email: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getArbeitszeitUsingGET(email: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getArbeitszeitUsingGET(email: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getArbeitszeitUsingGET(email: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling getArbeitszeitUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/settings/arbeitszeit/${encodeURIComponent(String(email))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }


}
